version: '3.8'

services:
  # Serviço para análise de código
  code-analyzer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      # Montar código fonte
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      # Montar diretório de resultados
      - ./results:/app/results
      # Montar arquivos de configuração (caso sejam alterados)
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./jest.config.js:/app/jest.config.js:ro
      - ./.eslintrc.js:/app/.eslintrc.js:ro
      - ./sonar-project.properties:/app/sonar-project.properties:ro
    environment:
      # Configurações opcionais do SonarQube
      - SONAR_HOST_URL=${SONAR_HOST_URL:-}
      - SONAR_TOKEN=${SONAR_TOKEN:-}
    networks:
      - analysis-network

  # Serviço SonarQube local (opcional)
  sonarqube:
    image: sonarqube:10.2-community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
      - sonar_extensions:/opt/sonarqube/extensions
    networks:
      - analysis-network
    profiles:
      - sonar-local

networks:
  analysis-network:
    driver: bridge

volumes:
  sonar_data:
  sonar_logs:
  sonar_extensions:
