version: '3.9'
services:
  analyzer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: tcc_analyzer:latest
    working_dir: /app
    environment:
      - SONAR_HOST_URL=${SONAR_HOST_URL}
      - SONAR_TOKEN=${SONAR_TOKEN}
    volumes:
      - ./:/app
    command: bash -lc "chmod +x scripts/analyze.sh && ./scripts/analyze.sh"
